# Generated by Django 4.0.3 on 2022-03-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_inventory_quantitiy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_add',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
